### ISSUE TITLE
aa_export_toBIDS validation fail

### ISSUE THREAD

**Issue by jones-michael-s** [rhodricusack/automaticanalysis#144] opened 2018-03-01 17:52 UTC
Hello all,

We've been trying out the aa BIDS functionality recently. After converting the output of an analysis to BIDS format using aa_export_toBIDS, I ran the validator (http://incf.github.io/bids-validator/) on it and got the following complaint:

```
 File Path: Repetition time did not match between the scan's header and the associated JSON metadata file.

 Type: Error
 File: sub-PL00016_task-block1_bold.nii.gz
 Location: BIDS/sub-PL00016/func/sub-PL00016_task-block1_bold.nii.gz
 Reason: Repetition time defined in the JSON (3.07 sec.) did not match the one 
 defined in the NIFTI header (0 sec.)
```

Is this a known problem? JP thought it might have something to do with SPM dicom-to-nifti conversion.

Mike

**Comment by tiborauer** [comment] 2018-03-01 18:38
Yes, it is a known issue, and it is, indeed caused by SPM (spm_file_merge).

**Comment by tiborauer** [comment] 2018-03-01 19:40
As you can see [here](https://www.nitrc.org/forum/forum.php?thread_id=6129&forum_id=1144), we should probably split the 4D file using fslsplit, then merge it back again with fslmerge, with the TR flag upon exporting.

**Comment by NADRIGOL** [comment] 2018-03-01 19:50
Just jumping in here without having much background in the existing code
for these tasks. But Matlab R2017b introduced built in niftiread and
niftiwrite functions which in my brief testing do a very good job with
headers/4D/nii.gz and other things I've found we usually work around a lot
with older solutions. I think aa has mostly avoided forcing matlab version
upgrades, but the new versions have shortened my own code and reduced
headaches recently.

Cheers,

Jacob Matthews

**Comment by jones-michael-s** [comment] 2018-03-02 17:07
Can't we just modify aamod_convert_epis to use FLS merge?

I played with this last night. I changed lines 508 ff:

```

if isfield(aap.options, 'NIFTI4D') && aap.options.NIFTI4D
   finalepis = finalepis{1};
   ind = find(finalepis=='-');
   finalepis = [finalepis(1:ind(2)-1) '.nii'];
   spm_file_merge(char({V0(ndummies+1:end).fname}),finalepis,0);
end

```

to:

```

if isfield(aap.options, 'NIFTI4D') && aap.options.NIFTI4D   
    finalepis = finalepis{1};
    ind = find(finalepis=='-');
    finalepis = [finalepis(1:ind(2)-1) '.nii'];     
    TR = DICOMHEADERS{1}.volumeTR;
    filelist = sprintf('%s ',V0.fname);
    cmd = sprintf('fslmerge -tr %s %s %f', finalepis, filelist, TR);
    [ err,~ ] = aas_runfslcommand(aap, cmd);
    if (err)
        aas_log(aap,false,'Warning: Using SPM for 4D file merge. File header will not include TR');
        spm_file_merge(char({V0(ndummies+1:end).fname}), finalepis, 0);
    end
end

```

Then imported an epi dicom, did some preprocessing on it, and exported the results to BIDS.

The validator no longer complains about the missing TR.

If this is on the right track, I could include the change in my next PR.

Mike

**Comment by tiborauer** [comment] 2018-03-02 17:16
Have you also checked that two two images (FSL and SPM) are identical when reading them in SPM?

**Comment by jones-michael-s** [comment] 2018-03-02 17:40
They appear to be the same.

Here's a tsdiffana summary for two conversions on the same epi (first used spm_merge, second used FSL):

![diagnostic_aamod_tsdiffana](https://user-images.githubusercontent.com/25826038/36912962-0fd1122e-1e0e-11e8-91fa-28aa36d72736.jpg)


![diagnostic_aamod_tsdiffana](https://user-images.githubusercontent.com/25826038/36912982-1f316304-1e0e-11e8-84f1-3b3d4bbfc9b4.jpg)

**Comment by tiborauer** [comment] 2018-03-02 17:57
Looks good to me. Could you, please, also check the difference image (again is SPM using e.g. ImCalc) if it contains only zeros?

**Comment by jones-michael-s** [comment] 2018-03-02 18:49
I should have though of that! :-)

Here's i1-i2 from imcalc:

![zero_difference](https://user-images.githubusercontent.com/25826038/36915933-0b82654c-1e18-11e8-8a2f-9943640ba5cb.jpg)

**Comment by jpeelle** [comment] 2018-04-18 14:44
Fixed by @tiborauer

**Closed by jpeelle** 2018-04-18 14:44 UTC
